-- Initial schema snapshot corresponding to database.GetMigrationModels and
-- database.getIndexes. This is deliberately explicit: future schema changes
-- must be added as new numbered migrations rather than AutoMigrate drift.
-- +goose Up

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE organizations (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), created_at timestamptz NOT NULL, updated_at timestamptz NOT NULL, deleted_at timestamptz, name varchar(255) NOT NULL, slug varchar(100) NOT NULL UNIQUE, settings jsonb DEFAULT '{}'::jsonb);
CREATE TABLE permissions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), created_at timestamptz NOT NULL, updated_at timestamptz NOT NULL, deleted_at timestamptz, resource varchar(50) NOT NULL, action varchar(20) NOT NULL, description varchar(200), UNIQUE(resource, action));
CREATE TABLE custom_roles (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), created_at timestamptz NOT NULL, updated_at timestamptz NOT NULL, deleted_at timestamptz, organization_id uuid NOT NULL, name varchar(100) NOT NULL, description varchar(500), is_system boolean DEFAULT false, is_default boolean DEFAULT false);
CREATE TABLE role_permissions (custom_role_id uuid NOT NULL, permission_id uuid NOT NULL, PRIMARY KEY (custom_role_id, permission_id));
CREATE TABLE users (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), created_at timestamptz NOT NULL, updated_at timestamptz NOT NULL, deleted_at timestamptz, organization_id uuid, email varchar(255) NOT NULL UNIQUE, password_hash varchar(255), full_name varchar(255), role_id uuid, settings jsonb DEFAULT '{}'::jsonb, is_active boolean DEFAULT true, is_available boolean DEFAULT true, is_super_admin boolean DEFAULT false, sso_provider varchar(50), sso_provider_id varchar(255));
CREATE TABLE user_organizations (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), created_at timestamptz NOT NULL, updated_at timestamptz NOT NULL, deleted_at timestamptz, user_id uuid NOT NULL, organization_id uuid NOT NULL, role_id uuid, is_default boolean DEFAULT false);
CREATE TABLE teams (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), created_at timestamptz NOT NULL, updated_at timestamptz NOT NULL, deleted_at timestamptz, organization_id uuid NOT NULL, name varchar(100) NOT NULL, description varchar(500), assignment_strategy varchar(50) DEFAULT 'round_robin', per_agent_timeout_secs integer DEFAULT 0, is_active boolean DEFAULT true, created_by_id uuid, updated_by_id uuid);
CREATE TABLE team_members (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), created_at timestamptz NOT NULL, updated_at timestamptz NOT NULL, deleted_at timestamptz, team_id uuid NOT NULL, user_id uuid NOT NULL, role varchar(50) DEFAULT 'agent', last_assigned_at timestamptz);
CREATE TABLE api_keys (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), created_at timestamptz NOT NULL, updated_at timestamptz NOT NULL, deleted_at timestamptz, organization_id uuid NOT NULL, user_id uuid NOT NULL, name varchar(255) NOT NULL, key_prefix varchar(16), key_hash varchar(255) NOT NULL, last_used_at timestamptz, expires_at timestamptz, is_active boolean DEFAULT true);
CREATE TABLE sso_providers (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), created_at timestamptz NOT NULL, updated_at timestamptz NOT NULL, deleted_at timestamptz, organization_id uuid NOT NULL, provider varchar(50) NOT NULL, client_id varchar(500) NOT NULL, client_secret varchar(500) NOT NULL, is_enabled boolean DEFAULT false, allow_auto_create boolean DEFAULT false, default_role_name varchar(50) DEFAULT 'agent', allowed_domains text, auth_url varchar(500), token_url varchar(500), user_info_url varchar(500));
CREATE TABLE webhooks (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), created_at timestamptz NOT NULL, updated_at timestamptz NOT NULL, deleted_at timestamptz, organization_id uuid NOT NULL, name varchar(255) NOT NULL, url text NOT NULL, events jsonb DEFAULT '[]'::jsonb, headers jsonb DEFAULT '{}'::jsonb, secret varchar(255), is_active boolean DEFAULT true);
CREATE TABLE custom_actions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), created_at timestamptz NOT NULL, updated_at timestamptz NOT NULL, deleted_at timestamptz, organization_id uuid NOT NULL, name varchar(100) NOT NULL, icon varchar(50), action_type varchar(20) NOT NULL, config jsonb DEFAULT '{}'::jsonb, is_active boolean DEFAULT true, display_order integer DEFAULT 0);
CREATE TABLE whatsapp_accounts (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), created_at timestamptz NOT NULL, updated_at timestamptz NOT NULL, deleted_at timestamptz, organization_id uuid NOT NULL, name varchar(100) NOT NULL, app_id varchar(100), phone_id varchar(100) NOT NULL, business_id varchar(100) NOT NULL, access_token text NOT NULL, app_secret varchar(255), webhook_verify_token varchar(255), api_version varchar(20) DEFAULT 'v21.0', is_default_incoming boolean DEFAULT false, is_default_outgoing boolean DEFAULT false, auto_read_receipt boolean DEFAULT false, business_calling_enabled boolean DEFAULT false, is_smb boolean DEFAULT false, status varchar(20) DEFAULT 'active', pin varchar(255), created_by_id uuid, updated_by_id uuid);
CREATE TABLE contacts (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), created_at timestamptz NOT NULL, updated_at timestamptz NOT NULL, deleted_at timestamptz, organization_id uuid NOT NULL, phone_number varchar(50) NOT NULL, profile_name varchar(255), whatsapp_account varchar(100), assigned_user_id uuid, last_message_at timestamptz, last_message_preview text, is_read boolean DEFAULT true, tags jsonb DEFAULT '[]'::jsonb, metadata jsonb DEFAULT '{}'::jsonb, last_inbound_at timestamptz, marketing_opt_out boolean DEFAULT false, bsuid varchar(150), chatbot_last_message_at timestamptz, chatbot_reminder_sent boolean DEFAULT false);
CREATE TABLE tags (organization_id uuid NOT NULL, name varchar(50) NOT NULL, color varchar(20), created_at timestamptz NOT NULL, updated_at timestamptz NOT NULL, PRIMARY KEY (organization_id, name));
CREATE TABLE messages (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), created_at timestamptz NOT NULL, updated_at timestamptz NOT NULL, deleted_at timestamptz, organization_id uuid NOT NULL, whatsapp_account varchar(100) NOT NULL, contact_id uuid NOT NULL, whats_app_message_id varchar(255), conversation_id varchar(255), direction varchar(10) NOT NULL, message_type varchar(20) NOT NULL, content text, media_url text, media_mime_type varchar(100), media_filename varchar(255), template_name varchar(255), template_params jsonb, interactive_data jsonb, flow_response jsonb, status varchar(20) DEFAULT 'pending', error_message text, is_reply boolean DEFAULT false, reply_to_message_id uuid, sent_by_user_id uuid, metadata jsonb DEFAULT '{}'::jsonb);
CREATE TABLE templates (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), created_at timestamptz NOT NULL, updated_at timestamptz NOT NULL, deleted_at timestamptz, organization_id uuid NOT NULL, whatsapp_account varchar(100) NOT NULL, meta_template_id varchar(100), name varchar(255) NOT NULL, display_name varchar(255), language varchar(10) NOT NULL, category varchar(50), status varchar(20) DEFAULT 'PENDING', quality_rating varchar(50) DEFAULT 'UNKNOWN', header_type varchar(20), header_content text, body_content text NOT NULL, footer_content text, buttons jsonb DEFAULT '[]'::jsonb, sample_values jsonb DEFAULT '[]'::jsonb, add_security_recommendation boolean DEFAULT false, code_expiration_minutes integer DEFAULT 0, created_by_id uuid, updated_by_id uuid);
CREATE TABLE whatsapp_flows (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), created_at timestamptz NOT NULL, updated_at timestamptz NOT NULL, deleted_at timestamptz, organization_id uuid NOT NULL, whatsapp_account varchar(100) NOT NULL, meta_flow_id varchar(100), name varchar(255) NOT NULL, status varchar(20) DEFAULT 'DRAFT', category varchar(50), json_version varchar(10) DEFAULT '6.0', flow_json jsonb, screens jsonb DEFAULT '[]'::jsonb, preview_url text, has_local_changes boolean DEFAULT true);
CREATE TABLE bulk_message_campaigns (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), created_at timestamptz NOT NULL, updated_at timestamptz NOT NULL, deleted_at timestamptz, organization_id uuid NOT NULL, whatsapp_account varchar(100) NOT NULL, name varchar(255) NOT NULL, template_id uuid NOT NULL, header_media_id text, header_media_filename text, header_media_mime_type text, header_media_local_path text, status varchar(20) DEFAULT 'draft', total_recipients integer DEFAULT 0, sent_count integer DEFAULT 0, delivered_count integer DEFAULT 0, read_count integer DEFAULT 0, failed_count integer DEFAULT 0, scheduled_at timestamptz, started_at timestamptz, completed_at timestamptz, created_by uuid NOT NULL, updated_by_id uuid);
CREATE TABLE bulk_message_recipients (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), created_at timestamptz NOT NULL, updated_at timestamptz NOT NULL, deleted_at timestamptz, campaign_id uuid NOT NULL, phone_number varchar(50) NOT NULL, recipient_name varchar(255), template_params jsonb DEFAULT '{}'::jsonb, header_params jsonb DEFAULT '{}'::jsonb, status varchar(20) DEFAULT 'pending', whats_app_message_id varchar(100), message_id uuid, error_message text, sent_at timestamptz, delivered_at timestamptz, read_at timestamptz);
CREATE TABLE notification_rules (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), created_at timestamptz NOT NULL, updated_at timestamptz NOT NULL, deleted_at timestamptz, organization_id uuid NOT NULL, whatsapp_account varchar(100) NOT NULL, name varchar(255) NOT NULL, is_enabled boolean DEFAULT true, trigger_type varchar(50) NOT NULL, trigger_config jsonb NOT NULL, template_id uuid NOT NULL, field_mappings jsonb DEFAULT '{}'::jsonb, conditions jsonb DEFAULT '{}'::jsonb, attachment_config jsonb);
CREATE TABLE chatbot_settings (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), created_at timestamptz NOT NULL, updated_at timestamptz NOT NULL, deleted_at timestamptz, organization_id uuid NOT NULL, whatsapp_account varchar(100), is_enabled boolean DEFAULT false, default_response text, greeting_buttons jsonb DEFAULT '[]'::jsonb, fallback_message text, fallback_buttons jsonb DEFAULT '[]'::jsonb, business_hours_enabled boolean DEFAULT false, business_hours jsonb DEFAULT '[]'::jsonb, out_of_hours_message text, allow_automated_outside_hours boolean DEFAULT true, allow_agent_queue_pickup boolean DEFAULT true, assign_to_same_agent boolean DEFAULT true, agent_current_conversation_only boolean DEFAULT false, sla_enabled boolean DEFAULT false, sla_response_minutes integer DEFAULT 15, sla_resolution_minutes integer DEFAULT 60, sla_escalation_minutes integer DEFAULT 30, sla_auto_close_hours integer DEFAULT 24, sla_auto_close_message text, sla_warning_message text, sla_escalation_notify_ids jsonb DEFAULT '[]'::jsonb, client_reminder_enabled boolean DEFAULT false, client_reminder_minutes integer DEFAULT 30, client_reminder_message text, client_auto_close_minutes integer DEFAULT 60, client_auto_close_message text, ai_enabled boolean DEFAULT false, ai_provider varchar(20), ai_api_key text, ai_model varchar(100), ai_max_tokens integer DEFAULT 500, ai_temperature decimal(3,2) DEFAULT 0.7, ai_system_prompt text, ai_include_history boolean DEFAULT true, ai_history_limit integer DEFAULT 4, session_timeout_mins integer DEFAULT 30, excluded_numbers jsonb DEFAULT '[]'::jsonb);
CREATE TABLE keyword_rules (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), created_at timestamptz NOT NULL, updated_at timestamptz NOT NULL, deleted_at timestamptz, organization_id uuid NOT NULL, whatsapp_account varchar(100) NOT NULL, name varchar(255) NOT NULL, is_enabled boolean DEFAULT true, priority integer DEFAULT 10, keywords jsonb NOT NULL, match_type varchar(20) DEFAULT 'contains', case_sensitive boolean DEFAULT false, response_type varchar(20) NOT NULL, response_content jsonb NOT NULL, conditions text, active_from timestamptz, active_until timestamptz, created_by_id uuid, updated_by_id uuid);
CREATE TABLE chatbot_flows (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), created_at timestamptz NOT NULL, updated_at timestamptz NOT NULL, deleted_at timestamptz, organization_id uuid NOT NULL, whatsapp_account varchar(100) NOT NULL, name varchar(255) NOT NULL, is_enabled boolean DEFAULT true, description text, trigger_keywords jsonb, trigger_button_id varchar(100), initial_message text, initial_message_type varchar(20) DEFAULT 'text', initial_template_id uuid, completion_message text, on_complete_action varchar(20), completion_config jsonb, timeout_message text, cancel_keywords jsonb, panel_config jsonb DEFAULT '{}'::jsonb, graph jsonb, created_by_id uuid, updated_by_id uuid);
CREATE TABLE chatbot_sessions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), created_at timestamptz NOT NULL, updated_at timestamptz NOT NULL, deleted_at timestamptz, organization_id uuid NOT NULL, contact_id uuid NOT NULL, whatsapp_account varchar(100) NOT NULL, phone_number varchar(50) NOT NULL, status varchar(20) DEFAULT 'active', current_flow_id uuid, current_step varchar(100), step_retries integer DEFAULT 0, session_data jsonb DEFAULT '{}'::jsonb, started_at timestamptz NOT NULL, last_activity_at timestamptz NOT NULL, completed_at timestamptz);
CREATE TABLE chatbot_session_messages (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), created_at timestamptz NOT NULL, updated_at timestamptz NOT NULL, deleted_at timestamptz, session_id uuid NOT NULL, direction varchar(10) NOT NULL, message text, step_name varchar(100));
CREATE TABLE ai_contexts (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), created_at timestamptz NOT NULL, updated_at timestamptz NOT NULL, deleted_at timestamptz, organization_id uuid NOT NULL, whatsapp_account varchar(100), name varchar(255) NOT NULL, is_enabled boolean DEFAULT true, priority integer DEFAULT 10, context_type varchar(20) NOT NULL, trigger_keywords jsonb, static_content text, api_config jsonb, created_by_id uuid, updated_by_id uuid);
CREATE TABLE agent_transfers (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), created_at timestamptz NOT NULL, updated_at timestamptz NOT NULL, deleted_at timestamptz, organization_id uuid NOT NULL, contact_id uuid NOT NULL, whatsapp_account varchar(100) NOT NULL, phone_number varchar(50) NOT NULL, status varchar(20) DEFAULT 'active', source varchar(20) DEFAULT 'manual', agent_id uuid, team_id uuid, transferred_by_user_id uuid, notes text, transferred_at timestamptz NOT NULL, resumed_at timestamptz, resumed_by uuid, sla_response_deadline timestamptz, sla_resolution_deadline timestamptz, sla_escalation_at timestamptz, expires_at timestamptz, picked_up_at timestamptz, first_response_at timestamptz, escalation_level integer DEFAULT 0, escalated_at timestamptz, sla_breached boolean DEFAULT false, sla_breached_at timestamptz);
CREATE TABLE user_availability_logs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL, organization_id uuid NOT NULL, is_available boolean NOT NULL, started_at timestamptz NOT NULL, ended_at timestamptz);
CREATE TABLE canned_responses (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), created_at timestamptz NOT NULL, updated_at timestamptz NOT NULL, deleted_at timestamptz, organization_id uuid NOT NULL, name varchar(100) NOT NULL, shortcut varchar(50), content text NOT NULL, category varchar(50), is_active boolean DEFAULT true, usage_count integer DEFAULT 0, buttons jsonb DEFAULT '[]'::jsonb, created_by_id uuid);
CREATE TABLE catalogs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), created_at timestamptz NOT NULL, updated_at timestamptz NOT NULL, deleted_at timestamptz, organization_id uuid NOT NULL, whatsapp_account varchar(100), meta_catalog_id varchar(100) UNIQUE, name varchar(255) NOT NULL, is_active boolean DEFAULT true);
CREATE TABLE catalog_products (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), created_at timestamptz NOT NULL, updated_at timestamptz NOT NULL, deleted_at timestamptz, organization_id uuid NOT NULL, catalog_id uuid NOT NULL, meta_product_id varchar(100) UNIQUE, name varchar(255) NOT NULL, description text, price bigint NOT NULL, currency varchar(3) DEFAULT 'USD', url varchar(500), image_url varchar(500), retailer_id varchar(100), is_active boolean DEFAULT true);
CREATE TABLE widgets (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), created_at timestamptz NOT NULL, updated_at timestamptz NOT NULL, deleted_at timestamptz, organization_id uuid NOT NULL, user_id uuid, name varchar(255) NOT NULL, description text, data_source varchar(50) NOT NULL, metric varchar(20) NOT NULL, field varchar(100), filters jsonb DEFAULT '[]'::jsonb, display_type varchar(20) DEFAULT 'number', chart_type varchar(20), group_by_field varchar(100), show_change boolean DEFAULT true, color varchar(20), size varchar(10) DEFAULT 'small', display_order integer DEFAULT 0, grid_x integer DEFAULT 0, grid_y integer DEFAULT 0, grid_w integer DEFAULT 0, grid_h integer DEFAULT 0, config jsonb DEFAULT '{}'::jsonb, is_shared boolean DEFAULT false, is_default boolean DEFAULT false);
CREATE TABLE conversation_notes (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), created_at timestamptz NOT NULL, updated_at timestamptz NOT NULL, deleted_at timestamptz, organization_id uuid NOT NULL, contact_id uuid NOT NULL, created_by_id uuid NOT NULL, content text NOT NULL);
CREATE TABLE call_logs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), created_at timestamptz NOT NULL, updated_at timestamptz NOT NULL, deleted_at timestamptz, organization_id uuid NOT NULL, whatsapp_account varchar(100) NOT NULL, contact_id uuid, whatsapp_call_id varchar(255), caller_phone varchar(50) NOT NULL, direction varchar(20) NOT NULL DEFAULT 'incoming', status varchar(20) NOT NULL DEFAULT 'ringing', duration integer DEFAULT 0, ivr_flow_id uuid, ivr_path jsonb, agent_id uuid, started_at timestamptz, answered_at timestamptz, ended_at timestamptz, disconnected_by varchar(20), error_message text, recording_s3_key varchar(500), recording_duration integer DEFAULT 0, recording_error text);
CREATE TABLE ivr_flows (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), created_at timestamptz NOT NULL, updated_at timestamptz NOT NULL, deleted_at timestamptz, organization_id uuid NOT NULL, whatsapp_account varchar(100) NOT NULL, name varchar(255) NOT NULL, description text, is_active boolean DEFAULT true, is_call_start boolean DEFAULT false, is_outgoing_end boolean DEFAULT false, menu jsonb, welcome_audio_url text, created_by_id uuid, updated_by_id uuid);
CREATE TABLE call_transfers (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), created_at timestamptz NOT NULL, updated_at timestamptz NOT NULL, deleted_at timestamptz, organization_id uuid NOT NULL, call_log_id uuid NOT NULL, whatsapp_call_id varchar(255) NOT NULL, caller_phone varchar(50) NOT NULL, contact_id uuid, whatsapp_account varchar(100) NOT NULL, status varchar(20) NOT NULL DEFAULT 'waiting', team_id uuid, agent_id uuid, initiating_agent_id uuid, transferred_at timestamptz NOT NULL, connected_at timestamptz, completed_at timestamptz, hold_duration integer DEFAULT 0, talk_duration integer DEFAULT 0, ivr_path jsonb, tried_agent_ids jsonb);
CREATE TABLE call_permissions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), created_at timestamptz NOT NULL, updated_at timestamptz NOT NULL, deleted_at timestamptz, organization_id uuid NOT NULL, contact_id uuid NOT NULL, whatsapp_account varchar(100) NOT NULL, status varchar(20) NOT NULL DEFAULT 'pending', message_id varchar(255), requested_at timestamptz NOT NULL, responded_at timestamptz, expires_at timestamptz, requested_by_id uuid);
CREATE TABLE audit_logs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL, resource_type varchar(50) NOT NULL, resource_id uuid NOT NULL, user_id uuid NOT NULL, user_name varchar(255) NOT NULL, action varchar(20) NOT NULL, changes jsonb DEFAULT '[]'::jsonb, created_at timestamptz NOT NULL);

CREATE UNIQUE INDEX idx_contacts_org_phone ON contacts(organization_id, phone_number);
CREATE INDEX idx_messages_contact_created ON messages(contact_id, created_at DESC);
CREATE INDEX idx_messages_conversation ON messages(conversation_id);
CREATE INDEX idx_contacts_assigned_read ON contacts(assigned_user_id, is_read);
CREATE INDEX idx_sessions_phone_status ON chatbot_sessions(organization_id, phone_number, status);
CREATE INDEX idx_keyword_rules_priority ON keyword_rules(organization_id, is_enabled, priority DESC);
CREATE INDEX idx_agent_transfers_active ON agent_transfers(organization_id, phone_number, status);
CREATE INDEX idx_agent_transfers_org_contact ON agent_transfers(organization_id, contact_id, status);
CREATE INDEX idx_agent_transfers_agent_active ON agent_transfers(agent_id, status) WHERE status = 'active';
CREATE INDEX idx_agent_transfers_team ON agent_transfers(team_id, status) WHERE team_id IS NOT NULL;
CREATE UNIQUE INDEX idx_whatsapp_accounts_org_phone ON whatsapp_accounts(organization_id, phone_id);
CREATE UNIQUE INDEX idx_templates_account_name_lang ON templates(whatsapp_account, name, language);
CREATE INDEX idx_keyword_rules_account ON keyword_rules(whatsapp_account, is_enabled, priority DESC);
CREATE INDEX idx_chatbot_flows_account ON chatbot_flows(whatsapp_account, is_enabled);
CREATE INDEX idx_ai_contexts_account ON ai_contexts(whatsapp_account, is_enabled, priority DESC);
CREATE INDEX idx_bulk_campaigns_account ON bulk_message_campaigns(whatsapp_account, status);
CREATE INDEX idx_notification_rules_account ON notification_rules(whatsapp_account, is_enabled);
CREATE INDEX idx_messages_account ON messages(whatsapp_account, created_at DESC);
CREATE INDEX idx_contacts_account ON contacts(whatsapp_account);
CREATE UNIQUE INDEX idx_canned_responses_org_name ON canned_responses(organization_id, name);
CREATE INDEX idx_canned_responses_active ON canned_responses(organization_id, is_active, usage_count DESC);
CREATE INDEX idx_webhooks_org_active ON webhooks(organization_id, is_active);
CREATE INDEX idx_availability_logs_user_time ON user_availability_logs(user_id, started_at DESC);
CREATE INDEX idx_availability_logs_org_time ON user_availability_logs(organization_id, started_at DESC);
CREATE UNIQUE INDEX idx_sso_providers_org_provider ON sso_providers(organization_id, provider);
CREATE INDEX idx_teams_org_active ON teams(organization_id, is_active);
CREATE UNIQUE INDEX idx_team_members_unique ON team_members(team_id, user_id) WHERE deleted_at IS NULL;
CREATE INDEX idx_team_members_user ON team_members(user_id);
CREATE UNIQUE INDEX idx_custom_roles_org_name ON custom_roles(organization_id, name);
CREATE INDEX idx_custom_roles_org_system ON custom_roles(organization_id, is_system);
CREATE INDEX idx_custom_roles_org_default ON custom_roles(organization_id, is_default) WHERE is_default = true;
CREATE INDEX idx_contacts_tags ON contacts USING GIN (tags);
CREATE UNIQUE INDEX idx_user_org_unique ON user_organizations(user_id, organization_id) WHERE deleted_at IS NULL;
CREATE INDEX idx_conversation_notes_contact ON conversation_notes(organization_id, contact_id, created_at DESC);
CREATE INDEX idx_call_logs_org_status ON call_logs(organization_id, status, created_at DESC);
CREATE INDEX idx_call_logs_contact ON call_logs(contact_id, created_at DESC);
CREATE INDEX idx_call_logs_wa_call_id ON call_logs(whatsapp_call_id) WHERE whatsapp_call_id != '';
CREATE INDEX idx_ivr_flows_org_active ON ivr_flows(organization_id, whatsapp_account, is_active);
CREATE UNIQUE INDEX idx_ivr_flows_org_call_start ON ivr_flows(organization_id, whatsapp_account) WHERE is_call_start = true AND is_active = true AND deleted_at IS NULL;

-- +goose Down
DROP TABLE IF EXISTS audit_logs, call_permissions, call_transfers, ivr_flows, call_logs, conversation_notes, widgets, catalog_products, catalogs, canned_responses, user_availability_logs, agent_transfers, ai_contexts, chatbot_session_messages, chatbot_sessions, chatbot_flows, keyword_rules, chatbot_settings, notification_rules, bulk_message_recipients, bulk_message_campaigns, whatsapp_flows, templates, messages, tags, contacts, whatsapp_accounts, custom_actions, webhooks, sso_providers, api_keys, team_members, teams, user_organizations, users, role_permissions, custom_roles, permissions, organizations CASCADE;
