<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue'
import { CalendarDays, Clock3, MessageSquare, Pencil, Plus, Users } from 'lucide-vue-next'
import { toast } from 'vue-sonner'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog'
import { PageHeader, ErrorState } from '@/components/shared'
import { accountsService, contactsService, clinicService, type ClinicAppointment, type ClinicPractitioner, type ClinicProfile, type ClinicService, type ClinicSlot, type ClinicWaitlistEntry } from '@/services/api'
import { getErrorMessage } from '@/lib/api-utils'

const profile = ref<ClinicProfile | null>(null)
const appointments = ref<ClinicAppointment[]>([])
const waitlist = ref<ClinicWaitlistEntry[]>([])
const loading = ref(true); const failed = ref(false)
const date = ref(new Date().toISOString().slice(0, 10))
const practitioners = ref<ClinicPractitioner[]>([]); const services = ref<ClinicService[]>([])
const accounts = ref<any[]>([]); const contacts = ref<any[]>([]); const slots = ref<ClinicSlot[]>([])
const bookingOpen = ref(false); const practitionerOpen = ref(false); const serviceOpen = ref(false); const bookingSaving = ref(false)
const profileOpen = ref(false); const rescheduleOpen = ref(false); const cancelOpen = ref(false); const selectedAppointment = ref<ClinicAppointment | null>(null); const appointmentSaving = ref(false)
const availabilityOpen = ref(false); const availabilityPractitioner = ref<ClinicPractitioner | null>(null); const availabilityRules = ref<Array<{ id: string; day_of_week: number; start_minute: number; end_minute: number; slot_interval_minutes: number }>>([])
const practitionerForm = ref({ display_name: '', department: '' }); const serviceForm = ref({ name: '', description: '', duration_minutes: 20, buffer_minutes: 0 })
const availabilityForm = ref({ day_of_week: 1, start: '09:00', end: '17:00', slot_interval_minutes: 20 })
const profileForm = ref({ display_name: '', timezone: 'Asia/Kolkata', address: '', reception_phone: '', booking_enabled: false, default_slot_minutes: 20, advance_booking_days: 30, minimum_notice_minutes: 30, cancellation_cutoff_minutes: 120 })
const rescheduleDate = ref(date.value); const rescheduleStartsAt = ref(''); const rescheduleSlots = ref<ClinicSlot[]>([]); const cancellationReason = ref('')
const booking = ref({ whatsapp_account: '', contact_id: '', practitioner_id: '', service_id: '', starts_at: '' })
const unpack = <T,>(response: any): T => response.data?.data ?? response.data
const nextDay = (day: string) => { const value = new Date(`${day}T00:00:00`); value.setDate(value.getDate() + 1); return value.toISOString().slice(0, 10) }
const patient = (item: ClinicAppointment) => item.contact?.profile_name || item.contact?.phone_number || 'Patient'
const time = (value: string) => new Intl.DateTimeFormat(undefined, { hour: 'numeric', minute: '2-digit' }).format(new Date(value))
const confirmed = computed(() => appointments.value.filter(x => x.status === 'confirmed').length)
const pending = computed(() => appointments.value.filter(x => x.status === 'pending').length)
const activeWaitlist = computed(() => waitlist.value.filter(x => x.status === 'waiting' || x.status === 'offered').length)
const actions = computed(() => [
  ...appointments.value.filter(x => x.status === 'pending').map(x => ({ key: x.id, label: `Confirm ${patient(x)}`, detail: `${time(x.starts_at)} · WhatsApp booking` })),
  ...waitlist.value.filter(x => x.status === 'offered').map(x => ({ key: x.id, label: 'Waitlist offer awaiting reply', detail: x.offer_expires_at ? `Expires ${time(x.offer_expires_at)}` : 'Awaiting reply' })),
])
async function load() {
  loading.value = true; failed.value = false
  try {
    const [p, a, w] = await Promise.all([clinicService.getProfile(), clinicService.listAppointments({ from: date.value, to: nextDay(date.value) }), clinicService.listWaitlist()])
    profile.value = unpack<{ configured: boolean; profile?: ClinicProfile }>(p).profile || null
    if (profile.value) Object.assign(profileForm.value, profile.value)
    appointments.value = unpack<{ appointments: ClinicAppointment[] }>(a).appointments || []
    waitlist.value = unpack<{ entries: ClinicWaitlistEntry[] }>(w).entries || []
    const [practitionerResult, serviceResult, accountResult, contactResult] = await Promise.all([clinicService.listPractitioners(), clinicService.listServices(), accountsService.list(), contactsService.list({ limit: 100 })])
    practitioners.value = unpack<{ practitioners: ClinicPractitioner[] }>(practitionerResult).practitioners || []
    services.value = unpack<{ services: ClinicService[] }>(serviceResult).services || []
    accounts.value = unpack<any>(accountResult).accounts || []
    contacts.value = unpack<any>(contactResult).contacts || []
  } catch (error) { failed.value = true; toast.error(getErrorMessage(error, 'Could not load clinic workspace')) } finally { loading.value = false }
}
onMounted(load)
watch(() => [booking.value.practitioner_id, booking.value.service_id, date.value], async () => {
  booking.value.starts_at = ''; slots.value = []
  if (!booking.value.practitioner_id) return
  try { slots.value = unpack<{ slots: ClinicSlot[] }>(await clinicService.listSlots(booking.value.practitioner_id, { date: date.value, service_id: booking.value.service_id || undefined })).slots || [] } catch { slots.value = [] }
})
async function addPractitioner() { try { await clinicService.createPractitioner(practitionerForm.value); practitionerOpen.value = false; practitionerForm.value = { display_name: '', department: '' }; await load(); toast.success('Practitioner added') } catch (e) { toast.error(getErrorMessage(e, 'Could not add practitioner')) } }
async function addService() { try { await clinicService.createService(serviceForm.value); serviceOpen.value = false; serviceForm.value = { name: '', description: '', duration_minutes: 20, buffer_minutes: 0 }; await load(); toast.success('Service added') } catch (e) { toast.error(getErrorMessage(e, 'Could not add service')) } }
async function bookAppointment() { bookingSaving.value = true; try { await clinicService.createAppointment({ ...booking.value, service_id: booking.value.service_id || undefined }); bookingOpen.value = false; booking.value = { whatsapp_account: '', contact_id: '', practitioner_id: '', service_id: '', starts_at: '' }; await load(); toast.success('Appointment confirmed') } catch (e) { toast.error(getErrorMessage(e, 'That slot is no longer available')) } finally { bookingSaving.value = false } }
const dayNames = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']
const asMinutes = (value: string) => { const [hour, minute] = value.split(':').map(Number); return hour * 60 + minute }
const asTime = (minutes: number) => `${String(Math.floor(minutes / 60)).padStart(2, '0')}:${String(minutes % 60).padStart(2, '0')}`
async function openAvailability(person: ClinicPractitioner) { availabilityPractitioner.value = person; availabilityOpen.value = true; try { availabilityRules.value = unpack<{ availability_rules: typeof availabilityRules.value }>(await clinicService.listAvailability(person.id)).availability_rules || [] } catch (e) { toast.error(getErrorMessage(e, 'Could not load availability')) } }
async function addAvailability() { if (!availabilityPractitioner.value) return; try { await clinicService.createAvailability(availabilityPractitioner.value.id, { day_of_week: availabilityForm.value.day_of_week, start_minute: asMinutes(availabilityForm.value.start), end_minute: asMinutes(availabilityForm.value.end), slot_interval_minutes: availabilityForm.value.slot_interval_minutes }); await openAvailability(availabilityPractitioner.value); toast.success('Availability saved') } catch (e) { toast.error(getErrorMessage(e, 'Could not save availability')) } }
async function saveProfile() { appointmentSaving.value = true; try { await clinicService.updateProfile(profileForm.value); profileOpen.value = false; await load(); toast.success('Clinic profile saved') } catch (e) { toast.error(getErrorMessage(e, 'Could not save clinic profile')) } finally { appointmentSaving.value = false } }
async function loadRescheduleSlots() { if (!selectedAppointment.value) return; rescheduleStartsAt.value = ''; try { rescheduleSlots.value = unpack<{ slots: ClinicSlot[] }>(await clinicService.listSlots(selectedAppointment.value.practitioner_id, { date: rescheduleDate.value, service_id: selectedAppointment.value.service_id })).slots || [] } catch (e) { rescheduleSlots.value = []; toast.error(getErrorMessage(e, 'Could not load availability')) } }
async function openReschedule(item: ClinicAppointment) { selectedAppointment.value = item; rescheduleDate.value = item.starts_at.slice(0, 10); rescheduleOpen.value = true; await loadRescheduleSlots() }
async function reschedule() { if (!selectedAppointment.value || !rescheduleStartsAt.value) return; appointmentSaving.value = true; try { await clinicService.rescheduleAppointment(selectedAppointment.value.id, rescheduleStartsAt.value); rescheduleOpen.value = false; await load(); toast.success('Appointment rescheduled') } catch (e) { toast.error(getErrorMessage(e, 'That slot is no longer available')) } finally { appointmentSaving.value = false } }
function openCancel(item: ClinicAppointment) { selectedAppointment.value = item; cancellationReason.value = ''; cancelOpen.value = true }
async function cancel() { if (!selectedAppointment.value) return; appointmentSaving.value = true; try { await clinicService.cancelAppointment(selectedAppointment.value.id, cancellationReason.value); cancelOpen.value = false; await load(); toast.success('Appointment cancelled') } catch (e) { toast.error(getErrorMessage(e, 'Could not cancel appointment')) } finally { appointmentSaving.value = false } }
</script>

<template>
  <div class="clinic-workspace flex h-full flex-col bg-background">
    <PageHeader title="Clinic workspace" description="Today’s appointments, WhatsApp replies, and reception actions." :icon="CalendarDays" icon-gradient="bg-gradient-to-br from-teal-500 to-emerald-600" />
    <ErrorState v-if="failed && !loading" class="flex-1" title="Couldn’t load the clinic workspace" description="Please try again." retry-label="Try again" @retry="load" />
    <main v-else class="flex-1 overflow-auto p-5 md:p-8"><section class="clinic-shell mx-auto max-w-7xl space-y-6">
      <Card v-if="!profile" class="setup-card border-teal-500/30"><CardHeader><span class="eyebrow">Nestam AI clinic operations</span><CardTitle class="text-2xl">Set up your clinic first</CardTitle><CardDescription>Add the minimum operational details Nestam AI needs to schedule safely.</CardDescription></CardHeader><CardContent><Button class="premium-primary" @click="profileOpen = true">Set up clinic</Button></CardContent></Card>
      <template v-else>
        <div class="clinic-hero flex flex-wrap items-end justify-between gap-4"><div><span class="eyebrow">Reception command centre</span><h2 class="mt-1 text-2xl font-semibold tracking-tight">{{ profile.display_name }}</h2><p class="mt-1 text-sm text-muted-foreground">Today’s clinic operations · {{ profile.timezone }}</p></div><div class="flex flex-wrap gap-2"><Button variant="outline" size="sm" @click="profileOpen = true"><Pencil class="mr-1 h-4 w-4" />Clinic setup</Button><Button v-if="practitioners.length && accounts.length && contacts.length" class="premium-primary" @click="bookingOpen = true"><Plus class="mr-2 h-4 w-4" />Book appointment</Button><Input v-model="date" type="date" class="date-control w-auto" @change="load" /><Button variant="outline" @click="load">Refresh</Button></div></div>
        <div class="grid gap-4 sm:grid-cols-3"><Card class="metric-card metric-confirmed"><CardContent class="flex gap-3 p-5"><Users class="metric-icon h-5 w-5" /><div><p class="text-3xl font-semibold tracking-tight">{{ confirmed }}</p><p class="text-sm text-muted-foreground">Confirmed today</p></div></CardContent></Card><Card class="metric-card metric-pending"><CardContent class="flex gap-3 p-5"><MessageSquare class="metric-icon h-5 w-5" /><div><p class="text-3xl font-semibold tracking-tight">{{ pending }}</p><p class="text-sm text-muted-foreground">Need confirmation</p></div></CardContent></Card><Card class="metric-card metric-waitlist"><CardContent class="flex gap-3 p-5"><Users class="metric-icon h-5 w-5" /><div><p class="text-3xl font-semibold tracking-tight">{{ activeWaitlist }}</p><p class="text-sm text-muted-foreground">Active waitlist</p></div></CardContent></Card></div>
        <div class="grid gap-5 lg:grid-cols-[1.45fr_0.8fr]"><Card><CardHeader><CardTitle>Today’s schedule</CardTitle><CardDescription>Live, tenant-scoped appointment calendar.</CardDescription></CardHeader><CardContent class="space-y-2"><div v-if="!appointments.length" class="rounded-xl border border-dashed p-8 text-center text-sm text-muted-foreground">No appointments for this day.</div><div v-for="item in appointments" :key="item.id" class="flex items-center gap-3 rounded-xl border p-3"><Clock3 class="h-4 w-4 text-muted-foreground" /><div class="min-w-0 flex-1"><p class="font-medium">{{ patient(item) }}</p><p class="text-sm text-muted-foreground">{{ time(item.starts_at) }} · {{ item.practitioner?.display_name || 'Practitioner' }}</p></div><Badge variant="secondary">{{ item.status }}</Badge><div v-if="item.status === 'pending' || item.status === 'confirmed'" class="flex gap-1"><Button size="sm" variant="outline" @click="openReschedule(item)">Move</Button><Button size="sm" variant="ghost" @click="openCancel(item)">Cancel</Button></div></div></CardContent></Card><Card><CardHeader><CardTitle>Next best actions</CardTitle><CardDescription>Items needing reception attention.</CardDescription></CardHeader><CardContent class="space-y-3"><p v-if="!actions.length" class="rounded-xl bg-muted/40 p-5 text-sm text-muted-foreground">All clear.</p><div v-for="action in actions" :key="action.key" class="rounded-xl border p-3"><p class="font-medium">{{ action.label }}</p><p class="mt-1 text-sm text-muted-foreground">{{ action.detail }}</p></div><RouterLink to="/contacts"><Button variant="outline" class="w-full">Open patient contacts</Button></RouterLink></CardContent></Card></div>
        <div class="grid gap-5 lg:grid-cols-2"><Card><CardHeader><div class="flex items-center justify-between"><div><CardTitle>Practitioners</CardTitle><CardDescription>People whose availability controls booking.</CardDescription></div><Button size="sm" variant="outline" @click="practitionerOpen = true"><Plus class="mr-1 h-4 w-4" />Add</Button></div></CardHeader><CardContent class="space-y-2"><p v-if="!practitioners.length" class="text-sm text-muted-foreground">Add a practitioner, then configure recurring availability.</p><div v-for="person in practitioners" :key="person.id" class="flex items-center justify-between rounded-lg border p-3"><div><p class="font-medium">{{ person.display_name }}</p><p class="text-sm text-muted-foreground">{{ person.department || 'General practice' }}</p></div><Button size="sm" variant="outline" @click="openAvailability(person)">Hours</Button></div></CardContent></Card><Card><CardHeader><div class="flex items-center justify-between"><div><CardTitle>Services</CardTitle><CardDescription>Service duration determines safe slots.</CardDescription></div><Button size="sm" variant="outline" @click="serviceOpen = true"><Plus class="mr-1 h-4 w-4" />Add</Button></div></CardHeader><CardContent class="space-y-2"><p v-if="!services.length" class="text-sm text-muted-foreground">Optional: default slot duration is used until services are added.</p><div v-for="service in services" :key="service.id" class="rounded-lg border p-3"><p class="font-medium">{{ service.name }}</p><p class="text-sm text-muted-foreground">{{ service.duration_minutes }} minutes<span v-if="service.buffer_minutes"> + {{ service.buffer_minutes }} minute buffer</span></p></div></CardContent></Card></div>
      </template>
    </section></main>
    <Dialog v-model:open="practitionerOpen"><DialogContent><DialogHeader><DialogTitle>Add practitioner</DialogTitle><DialogDescription>Only operational scheduling details are stored.</DialogDescription></DialogHeader><div class="space-y-3"><div><Label>Name</Label><Input v-model="practitionerForm.display_name" /></div><div><Label>Department</Label><Input v-model="practitionerForm.department" placeholder="Optional" /></div></div><DialogFooter><Button :disabled="!practitionerForm.display_name" @click="addPractitioner">Add practitioner</Button></DialogFooter></DialogContent></Dialog>
    <Dialog v-model:open="serviceOpen"><DialogContent><DialogHeader><DialogTitle>Add service</DialogTitle></DialogHeader><div class="space-y-3"><div><Label>Service name</Label><Input v-model="serviceForm.name" /></div><div><Label>Duration (minutes)</Label><Input v-model.number="serviceForm.duration_minutes" type="number" min="5" /></div><div><Label>Buffer (minutes)</Label><Input v-model.number="serviceForm.buffer_minutes" type="number" min="0" /></div></div><DialogFooter><Button :disabled="!serviceForm.name" @click="addService">Add service</Button></DialogFooter></DialogContent></Dialog>
    <Dialog v-model:open="availabilityOpen"><DialogContent><DialogHeader><DialogTitle>Weekly hours · {{ availabilityPractitioner?.display_name }}</DialogTitle><DialogDescription>These rules are evaluated in the clinic time zone for both reception and WhatsApp booking.</DialogDescription></DialogHeader><div class="space-y-3"><div class="grid grid-cols-3 gap-2"><div><Label>Day</Label><select v-model.number="availabilityForm.day_of_week" class="w-full rounded-md border bg-background p-2"><option v-for="(day, index) in dayNames" :key="day" :value="index">{{ day }}</option></select></div><div><Label>Start</Label><Input v-model="availabilityForm.start" type="time" /></div><div><Label>End</Label><Input v-model="availabilityForm.end" type="time" /></div></div><div><Label>Slot interval</Label><Input v-model.number="availabilityForm.slot_interval_minutes" type="number" min="5" /></div><div class="max-h-40 space-y-2 overflow-auto rounded-lg border p-3"><p v-if="!availabilityRules.length" class="text-sm text-muted-foreground">No weekly hours added yet.</p><p v-for="rule in availabilityRules" :key="rule.id" class="text-sm">{{ dayNames[rule.day_of_week] }} · {{ asTime(rule.start_minute) }}–{{ asTime(rule.end_minute) }} · every {{ rule.slot_interval_minutes }} min</p></div></div><DialogFooter><Button :disabled="!availabilityPractitioner || availabilityForm.start >= availabilityForm.end" @click="addAvailability">Add hours</Button></DialogFooter></DialogContent></Dialog>
    <Dialog v-model:open="bookingOpen"><DialogContent><DialogHeader><DialogTitle>Book appointment</DialogTitle><DialogDescription>Final availability is checked again by the server when you confirm.</DialogDescription></DialogHeader><div class="space-y-3"><div><Label>WhatsApp account</Label><select v-model="booking.whatsapp_account" class="w-full rounded-md border bg-background p-2"><option value="">Select account</option><option v-for="account in accounts" :key="account.id" :value="account.name">{{ account.name }}</option></select></div><div><Label>Patient</Label><select v-model="booking.contact_id" class="w-full rounded-md border bg-background p-2"><option value="">Select patient</option><option v-for="contact in contacts.filter((c:any) => !booking.whatsapp_account || c.whatsapp_account === booking.whatsapp_account)" :key="contact.id" :value="contact.id">{{ contact.profile_name || contact.phone_number }}</option></select></div><div><Label>Practitioner</Label><select v-model="booking.practitioner_id" class="w-full rounded-md border bg-background p-2"><option value="">Select practitioner</option><option v-for="person in practitioners" :key="person.id" :value="person.id">{{ person.display_name }}</option></select></div><div><Label>Service</Label><select v-model="booking.service_id" class="w-full rounded-md border bg-background p-2"><option value="">Default slot</option><option v-for="service in services" :key="service.id" :value="service.id">{{ service.name }}</option></select></div><div><Label>Available time on {{ date }}</Label><select v-model="booking.starts_at" class="w-full rounded-md border bg-background p-2" :disabled="!booking.practitioner_id"><option value="">Select a time</option><option v-for="slot in slots" :key="slot.starts_at" :value="slot.starts_at">{{ time(slot.starts_at) }}</option></select></div></div><DialogFooter><Button :disabled="bookingSaving || !booking.whatsapp_account || !booking.contact_id || !booking.practitioner_id || !booking.starts_at" @click="bookAppointment">{{ bookingSaving ? 'Confirming…' : 'Confirm appointment' }}</Button></DialogFooter></DialogContent></Dialog>
    <Dialog v-model:open="profileOpen"><DialogContent><DialogHeader><DialogTitle>Clinic setup</DialogTitle><DialogDescription>Operational scheduling details only. Do not add clinical notes or patient records here.</DialogDescription></DialogHeader><div class="grid gap-3 sm:grid-cols-2"><div><Label>Clinic name</Label><Input v-model="profileForm.display_name" /></div><div><Label>Time zone</Label><Input v-model="profileForm.timezone" placeholder="Asia/Kolkata" /></div><div><Label>Reception phone</Label><Input v-model="profileForm.reception_phone" /></div><div><Label>Default slot minutes</Label><Input v-model.number="profileForm.default_slot_minutes" type="number" min="5" /></div><div class="sm:col-span-2"><Label>Address</Label><Input v-model="profileForm.address" /></div><label class="flex items-center gap-2 sm:col-span-2"><input v-model="profileForm.booking_enabled" type="checkbox" /> Enable WhatsApp appointment booking</label></div><DialogFooter><Button :disabled="appointmentSaving || !profileForm.display_name || !profileForm.timezone" @click="saveProfile">{{ appointmentSaving ? 'Saving…' : 'Save clinic setup' }}</Button></DialogFooter></DialogContent></Dialog>
    <Dialog v-model:open="rescheduleOpen"><DialogContent><DialogHeader><DialogTitle>Move appointment</DialogTitle><DialogDescription>{{ patient(selectedAppointment!) }} · fresh availability is checked before saving.</DialogDescription></DialogHeader><div class="space-y-3"><div><Label>Date</Label><Input v-model="rescheduleDate" type="date" @change="loadRescheduleSlots" /></div><div><Label>Available time</Label><select v-model="rescheduleStartsAt" class="w-full rounded-md border bg-background p-2"><option value="">Select a time</option><option v-for="slot in rescheduleSlots" :key="slot.starts_at" :value="slot.starts_at">{{ time(slot.starts_at) }}</option></select></div></div><DialogFooter><Button :disabled="appointmentSaving || !rescheduleStartsAt" @click="reschedule">{{ appointmentSaving ? 'Saving…' : 'Confirm new time' }}</Button></DialogFooter></DialogContent></Dialog>
    <Dialog v-model:open="cancelOpen"><DialogContent><DialogHeader><DialogTitle>Cancel appointment</DialogTitle><DialogDescription>This is retained as an auditable cancellation and may trigger an eligible waitlist offer.</DialogDescription></DialogHeader><div><Label>Reason (optional)</Label><Input v-model="cancellationReason" placeholder="e.g. Patient requested cancellation" /></div><DialogFooter><Button variant="destructive" :disabled="appointmentSaving" @click="cancel">{{ appointmentSaving ? 'Cancelling…' : 'Cancel appointment' }}</Button></DialogFooter></DialogContent></Dialog>
  </div>
</template>

<style scoped>
.clinic-workspace { background: radial-gradient(circle at 82% -10%, rgb(20 184 166 / 0.13), transparent 31%), linear-gradient(180deg, hsl(var(--background)), hsl(var(--muted) / 0.32)); }
.clinic-shell { padding-bottom: 2rem; }
.clinic-hero { border: 1px solid rgb(45 212 191 / 0.2); border-radius: 1rem; padding: 1.35rem; background: linear-gradient(120deg, rgb(15 118 110 / 0.09), transparent 55%); box-shadow: 0 12px 32px rgb(15 23 42 / 0.05); }
.eyebrow { color: rgb(13 148 136); font-size: .7rem; font-weight: 700; letter-spacing: .12em; text-transform: uppercase; }
.premium-primary { background: linear-gradient(135deg, rgb(13 148 136), rgb(5 150 105)); box-shadow: 0 8px 18px rgb(13 148 136 / .22); }
.premium-primary:hover { filter: brightness(1.06); transform: translateY(-1px); }
.date-control { border-color: rgb(20 184 166 / .3); background: hsl(var(--background) / .8); }
.metric-card { overflow: hidden; position: relative; border-color: rgb(148 163 184 / .18); box-shadow: 0 8px 22px rgb(15 23 42 / .045); }
.metric-card::after { content: ''; position: absolute; inset: 0 auto 0 0; width: 4px; background: currentColor; }
.metric-confirmed { color: rgb(5 150 105); }.metric-pending { color: rgb(217 119 6); }.metric-waitlist { color: rgb(13 148 136); }
.metric-card :deep(p) { color: inherit; }.metric-card :deep(.text-muted-foreground) { color: hsl(var(--muted-foreground)); }.metric-icon { margin-top: .25rem; }
.setup-card { background: linear-gradient(135deg, rgb(240 253 250 / .9), hsl(var(--card))); box-shadow: 0 20px 45px rgb(15 118 110 / .08); }
:global(.dark) .setup-card { background: linear-gradient(135deg, rgb(15 118 110 / .13), hsl(var(--card))); }
@media (max-width: 640px) { .clinic-hero { padding: 1rem; } }
</style>
